### ISSUE TITLE
请教SSDT-SBUS-MCHC.aml的作用

### ISSUE THREAD

**Issue by malash** [xiaoyaowx/Hackintosh-Z490-ASRock-Steel-Legend-Intel-10700#1]
你好，我看到这个提交 https://github.com/xiaoyaowx/Hackintosh-Z490-ASRock-Steel-Legend-Intel-10700/commit/c19a2801a0179a730cdc67178638c84054a2ccc5 里新加了 `SSDT-SBUS-MCHC.aml`，请问它的作用是什么呢？

**Comment by xiaoyaowx** [comment]
修复SMBus控制器
https://dortania.github.io/Getting-Started-With-ACPI/Universal/smbus.html

**Comment by malash** [comment]
非常感谢🙏
